POST http://localhost:5000/movies
content-type: application/json

{
    "name": "Inception",
    "language": "English",
    "runtime": 148,
    "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster."
}

###

GET http://localhost:5000/movies
content-type: application/json

###

GET http://localhost:5000/movies/85a1f2c8-0abc-42ab-bb74-8f7968268ab5
content-type: application/json

###

PUT http://localhost:5000/movies/85a1f2c8-0abc-42ab-bb74-8f7968268ab5
content-type: application/json

{
    "name": "Inception",
    "language": "English",
    "runtime": 148,
    "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster."
}

###

DELETE http://localhost:5000/movies/85a1f2c8-0abc-42ab-bb74-8f7968268ab5

