# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x06models\"\x80\x01\n\nMovieProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0f\n\x07\x63reated\x18\x06 \x01(\t\x12\x0f\n\x07updated\x18\x07 \x01(\t')



_MOVIEPROTO = DESCRIPTOR.message_types_by_name['MovieProto']
MovieProto = _reflection.GeneratedProtocolMessageType('MovieProto', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEPROTO,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:models.MovieProto)
  })
_sym_db.RegisterMessage(MovieProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIEPROTO._serialized_start=24
  _MOVIEPROTO._serialized_end=152
# @@protoc_insertion_point(module_scope)
